---
- name: Configure IP Addresses
  hosts: nxos1
  tasks:
    - name: Configure IP Addresses
      nxos_ip_interface:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        transport: nxapi
        interface: "{{ item.intf }}"
        version: v4
        state: present
        addr: "{{ item.addr }}"
        mask: 30 
      with_items:
        - {intf: Ethernet 2/1, addr: 10.1.3.1}
        - {intf: Ethernet 2/2, addr: 10.1.3.5}
        - {intf: Ethernet 2/3, addr: 10.1.3.9}
        - {intf: Ethernet 2/4, addr: 10.1.3.13}
