---

- name: Nexus VLAN
  hosts: nexus 
  gather_facts: false

  vars:
    device:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        transport: nxapi

  tasks:
    - name: Nexus VLAN
      nxos_vlan:
        provider: "{{ device }}"
        vlan_id: 501
        name: RED
        vlan_state: active

